# Generated by Django 3.2.9 on 2023-01-18 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Room',
            new_name='poetry',
        ),
    ]
