# Generated by Django 3.2.9 on 2023-01-22 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_about'),
    ]

    operations = [
        migrations.DeleteModel(
            name='about',
        ),
    ]
